<<<<<<< HEAD
﻿name: Run tests on any Push event
=======
name: Run tests on any Push event
>>>>>>> 39d24d4084b751bc60f8069846e00b7ec1024643
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
#      - name: Run tests
#        run: coverage run tests.py
#      - name: Tests report
#        run: coverage report



